### ISSUE TITLE
Got Endpoint is not defined error

### ISSUE THREAD

**Issue by chyf-md** [datarobot/airflow-provider-datarobot#2]
Hi,

I created the connection but found the DataRobot endpoint and credentials were not listed in the connection table.
I tried the CreateProjectOperator and got below errors:

```
[2022-03-28, 13:08:09 UTC] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=datarobot_test, task_id=create_project, execution_date=20220328T050806, start_date=20220328T050809, end_date=20220328T050809
[2022-03-28, 13:08:09 UTC] {standard_task_runner.py:89} ERROR - Failed to execute job 29 for task create_project
Traceback (most recent call last):
  File "/Users/yafang.chang/Documents/Projects/airflow/env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/yafang.chang/Documents/Projects/airflow/env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/yafang.chang/Documents/Projects/airflow/env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/yafang.chang/Documents/Projects/airflow/env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/yafang.chang/Documents/Projects/airflow/env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/yafang.chang/Documents/Projects/airflow/env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/yafang.chang/Documents/Projects/airflow/env/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/yafang.chang/Documents/Projects/airflow/env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/yafang.chang/Documents/Projects/airflow/env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/yafang.chang/Documents/Projects/airflow/env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/Users/yafang.chang/Documents/Projects/airflow/env/lib/python3.9/site-packages/datarobot_provider/operators/datarobot.py", line 50, in execute
    DataRobotHook(datarobot_conn_id=self.datarobot_conn_id).run()
  File "/Users/yafang.chang/Documents/Projects/airflow/env/lib/python3.9/site-packages/datarobot_provider/hooks/datarobot.py", line 73, in run
    self.get_conn()
  File "/Users/yafang.chang/Documents/Projects/airflow/env/lib/python3.9/site-packages/datarobot_provider/hooks/datarobot.py", line 65, in get_conn
    raise AirflowException("Endpoint is not defined")
airflow.exceptions.AirflowException: Endpoint is not defined
```

The dag is like below:

```
from datetime import datetime

from airflow.decorators import dag

from datarobot_provider.operators.datarobot import (
    CreateProjectOperator,
    DeployRecommendedModelOperator,
    ScorePredictionsOperator,
    TrainModelsOperator,
)
from datarobot_provider.sensors.datarobot import AutopilotCompleteSensor, ScoringCompleteSensor


@dag(
    schedule_interval=None,
    start_date=datetime(2022, 1, 1),
    tags=['example'],
)
def datarobot_test():
    create_project_op = CreateProjectOperator(task_id='create_project')
    (
        create_project_op
    )


datarobot_test_dag = datarobot_test()
```

I tested on my Laptop with airflow 2.2.4. Could you please provide some advice? Thank you.

**Comment by chyf-md** [comment]
This is an environment issue. Please ignore it. Thank you.
